### ISSUE TITLE
The identifier "index" isn't declared.

### ISSUE THREAD

**Issue by Maka-A-P** [thejustinwalsh/castledb-godot#6]
Hi, I'm having trouble loading your plugin, it feels like it isn't generating everything it should.
When I load plugin and singleton, i get the error "(28,1): The identifier "index" isn't declared in the current scope."
I get the feeling an array called "index" where you store just the Unique Identifier for a quick check should be there, but it's not.
All the code I get from "Database.cdb" is in the pic.
![Capture](https://user-images.githubusercontent.com/56448634/107625842-344aae80-6c5d-11eb-87dc-77de5fffd846.PNG)

**Comment by thejustinwalsh** [comment]
It does look like the code failed to generate the mapping table, not sure why though? If you wouldn't mind attaching a sample input DB that breaks it, I can take a look and debug through it.

**Comment by Maka-A-P** [comment]
Yeah sure, here's the original file:

[DB.zip](https://github.com/thejustinwalsh/castledb-godot/files/5967918/DB.zip)

**Comment by Maka-A-P** [comment]
Any news about it? I really want to use this plugin for a quick project, and I really hate making databases.

**Comment by thejustinwalsh** [comment]
Been a busy week.

Off the top of my head I am guessing there there may be some conflict with column names? There is also the possibility that something changed in a more recent version of Godot as well.

It would be worth trying to a few simple DB’s first to see if the same problem exists, as this may help you isolate the conflict.

**Comment by thejustinwalsh** [comment]
I see what happened here. I should add a note to the docs.

At least 1 column marked as a `Unique Identifier` is required for this plugin to function.

![image](https://user-images.githubusercontent.com/72912/108723938-07f72380-74e2-11eb-8c9c-918bf2918012.png)

I changed your id column from `Text` to `Unique Identifier` and everything is working as expected.
